l_english:
 CONFIGURATOR_TOOLTIP:0 "Set up your game"
 
 nw_configurator_title:0 "§RMod Configurator§!"
 
 #1 ряд
 ger_title:0 "§HGermany:§!"
 ger_reich:0 "Path of the Third Reich"
 ger_kaiser:0 "Path of the Kaiser"
 ger_revolt:0 "Path of the Revolutionary Reich"
 ger_democrat:0 "Democratic Path"
 
 hun_title:0 "§HHungary:§!"
 hun_hbbrg:0 "Restore the Habsburg Empire"
 hbbrg_fash:0 "Habsburg Empire: Path of the Christian Empire"
 hbbrg_monarch:0 "Habsburg Empire: Path of Austria-Hungary"
 hbbrg_danubian:0 "Habsburg Empire: Path of the Danube Federation/USE"
 
 fra_title:0 "§HFrance:§!"
 fra_little_entente:0 "Path of the «Little Entente»"
 fra_go_with_britain:0 "Go with Britain"
 fra_support_the_left:0 "Communist Path"
 fra_support_the_right:0 "Fascist Path"
 fra_support_tro:0 "Trotskyist Path"
 
 mex_title:0 "§HMexico§!"
 mex_commi:0 "Communist Path"
 mex_troz:0 "Trotskyist Path"
 mex_fash:0 "Fascist Path"
 mex_dem:0 "Democratic Path"
 
 jap_title:0 "§HJapan§!"
 jap_troz:0 "Trotskyist Path"
 jap_commi:0 "Communist Path"
 jap_nokodoha:0 "Fight against «Kodoha»"
 jap_kodoha:0 "Support «Kodoha»"
 jap_dem:0 "Democratic Path"
 
 man_title:0 "§HManchukuo§!"
 man_obedience:0 "Obedience"
 man_aggressiveness:0 "Aggression"
 
 tur_title:0 "§HTurkey§!"
 tur_neut_ismet_inenu:0 "Path of the İsmet İnönü"
 tur_neut_cakmak:0 "Path of the Çakmak"
 tur_dem:0 "Democratic Path"
 tur_fash:0 "Fascist Path"
 tur_troz:0 "Trotskyist Path"
 tur_commi:0 "Communist Path"
 tur_monarch:0 "Monarchic Path"
 
 #2 ряд
 can_title:0 "§HCanada:§!"
 can_with_uk:0 "Go with Britain"
 can_naa:0 "North American Alliance"
 can_fash:0 "Fascist Path"
 can_commi:0 "Communist Path"
 
 saf_title:0 "§HSouth Africa:§!"
 saf_with_uk:0 "Go with Britain"
 saf_fash:0 "Fascist Path"
 saf_commi:0 "Communist Path"
 
 raj_title:0 "§HIndia:§!"
 raj_with_uk:0 "Go with Britain"
 raj_fash:0 "Fascist Path"
 raj_commi:0 "Communist Path"
 
 ast_title:0 "§HAustralia:§!"
 ast_with_uk:0 "Go with Britain"
 ast_self:0 "Independence"
 ast_fash:0 "Fascist Path"
 ast_commi:0 "Communist Path"
 
 nzl_title:0 "§HNew Zealand§!"
 nzl_with_uk:0 "Go with Britain"
 nzl_self:0 "Independence"
 nzl_fash:0 "Fascist Path"
 nzl_commi:0 "Communist Path"
 
 generic_all_flag:0 "§MConfiguration is selected in the configurator§!"
 
 RESET_CONFIGURATOR_TOOLTIP:0 "Resetting Priorities"
 ENEMY_SWITCH_TOOLTIP:0 "Activating Priority for the AI Player"
 GENERIC_TOOLTIP:0 "§RGeneric focuses will be fully unlocked§!"
 RANDOM_TOOLTIP:0 "§RGenerate random checkboxes!§!"
 
 NW_conf_on:0 "£trigger_yes"
 NW_conf_off:0 "£trigger_no"
 
 