l_english:
 CONFIGURATOR_TOOLTIP:0 "Set up your game"
 
 nw_configurator_title:0 "§RMod Configurator§!"
 
 #1 ряд
 ger_title:0 "§HGermany:§!"
 ger_reich:0 "Path Of The Third Reich"
 ger_kaiser:0 "The Path Of The Kaiser"
 ger_revolt:0 "The path of the revolutionary Reich"
 ger_democrat:0 "Democratic way"
 
 hun_title:0 "§HHungary:§!"
 hun_hbbrg:0 "Restore the Habsburg Empire"
 hbbrg_fash:0 "Habsburg Empire:the way of the Christian Empire"
 hbbrg_monarch:0 "Habsburg Empire:the way of Austria-Hungary"
 hbbrg_danubian:0 "Habsburg Empire:the way of the Danube Federation/USA"
 
 fra_title:0 "§HFrance:§!"
 fra_little_entente:0 The path of the "Little Entente""
 fra_go_with_britain:0 "Go with britain"
 fra_support_the_left:0 "The Communist way"
 fra_support_the_right:0 "The fascist way"
 fra_support_tro:0 "The Trotskyist way"
 
 mex_title:0 "§HMexico§!"
 mex_commi:0 "The Communist way"
 mex_troz:0 "The Trotskyist way"
 mex_fash:0 "The fascist way"
 mex_dem:0 "Democratic way"
 
 jap_title:0 "§HJapan§!"
 jap_troz:0 "The Trotskyist way"
 jap_commi:0 "The Communist way"
 jap_nokodoha:0 "Fight against "Kоdоha""
 jap_kodoha:0 "Support "Kоdоha""
 jap_dem:0 "Democratic way"
 
 man_title:0 "§HManchukuo§!"
 man_obedience:0 "Obedience"
 man_aggressiveness:0 "Aggression"
 
 tur_title:0 "§HTurkey§!"
 tur_neut_ismet_inenu:0 "The Way Ismet Inonu"
 tur_neut_cakmak:0 "The Way Of Chakmak"
 tur_dem:0 "Democratic way"
 tur_fash:0 "The fascist way"
 tur_troz:0 "The Trotskyist way"
 tur_commi:0 "The Communist way"
 tur_monarch:0 "Monarchic path"
 
 #2 ряд
 can_title:0 "§HCanada:§!"
 can_with_uk:0 "Go with britain"
 can_naa:0 "North American Alliance"
 can_fash:0 "The fascist way"
 can_commi:0 "The Communist way"
 
 saf_title:0 "§HSouth Africa:§!"
 saf_with_uk:0 "Go with britain"
 saf_fash:0 "The fascist way"
 saf_commi:0 "The Communist way"
 
 raj_title:0 "§HIndia:§!"
 raj_with_uk:0 "Go with britain"
 raj_fash:0 "The fascist way"
 raj_commi:0 "The Communist way"
 
 ast_title:0 "§HAustralia:§!"
 ast_with_uk:0 "Go with britain"
 ast_self:0 "Independence"
 ast_fash:0 "The fascist way"
 ast_commi:0 "The Communist way"
 
 nzl_title:0 "§HНовая Зеландия:§!"
 nzl_with_uk:0 "Go with britain"
 nzl_self:0 "Independence"
 nzl_fash:0 "The fascist way"
 nzl_commi:0 "The Communist way"
 
 generic_all_flag:0 "§MВыбрана настройка в конфигураторе§!"
 
 RESET_CONFIGURATOR_TOOLTIP:0 "Resetting priorities"
 ENEMY_SWITCH_TOOLTIP:0 "Activating priority for the AI player"
 GENERIC_TOOLTIP:0 "§RGenerik focuses will be fully unlocked§!"
 RANDOM_TOOLTIP:0 "§RСгенерить рандомные галочки!§!"
 
 NW_conf_on:0 "£trigger_yes"
 NW_conf_off:0 "£trigger_no"
 
 